// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klgevbvjlwrqrcrbcvzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsZ2V2YnZqbHdycXJjcmJjdnpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1Mjk4OTYsImV4cCI6MjA1NzEwNTg5Nn0.cFnL8BDEupB5HJECGFa0ULnhxoqgZO2BpDZgguhijiI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);